/* eslint-disable */
// Generated by Wrangler by running `wrangler types server-collector/bindings.d.ts --config server-collector/wrangler.jsonc --env-interface CollectorEnv --include-runtime=false` (hash: 89dc3ebfe32bec88b677d8a31787bb67)
interface __BaseEnv_CollectorEnv {
	BROWSER: Fetcher;
	CONSENT_VERSION: "2026-09-11";
	CONNECTIONS: DurableObjectNamespace<import("./index").ReceiptConnection>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ReceiptConnection";
	}
	interface Env extends __BaseEnv_CollectorEnv {}
}
interface CollectorEnv extends __BaseEnv_CollectorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONSENT_VERSION">> {}
}
