import type { Source } from './receipts';
export const providers:{id:Source;name:string;mode:string;color:string;url:string;steps:string[];note:string}[]=[
{id:'hipass',name:'하이패스 · 통행료',mode:'날짜별 자동 조회 · 검증 중',color:'#49654a',url:'https://www.hipass.co.kr/usepculr/InitUsePculrTabSearch.do',steps:['고속도로 통행료 홈페이지 계정으로 로그인하세요.','계정에 등록된 하이패스 카드의 사용내역을 출장 날짜별로 조회합니다.','카드 등록이나 본인 인증은 공식 사이트에서 먼저 마쳐야 할 수 있습니다.'],note:'회원 조회 어댑터를 추가했습니다. 실제 회원 내역 대조는 아직 필요합니다. 저장 PDF는 공식 조회 내역의 사본이며 사업자 발급 영수증과 구분됩니다.'},
{id:'transit',name:'티머니 · 지하철·시내버스',mode:'회원 내역 자동 조회',color:'#c76221',url:'https://pay.tmoney.co.kr/ncs/pct/mtmn/ReadTrprInqr.dev',steps:['티머니 계정에 등록된 선불·모바일 교통카드가 대상입니다.','공식 조회 기간은 조회일 기준 367일 전부터 2일 전까지입니다.','신용·체크카드의 후불교통 내역은 발행 카드사에서 제공됩니다.'],note:'홈서버에서 등록 카드와 조회 페이지를 순회합니다. 실제 회원 계정의 최종 대조는 아직 필요합니다. 저장하는 PDF는 공식 조회 내역의 사본입니다.'},
{id:'ktx',name:'KTX · 코레일',mode:'날짜별 자동 조회',color:'#144faf',url:'https://www.korail.com/',steps:['출장 다녀온 날짜를 여러 개 선택하세요.','코레일 로그인 창에서 로그인과 필요한 인증을 마치세요.','로그인이 확인되면 날짜별 내역 조회와 영수증 PDF 저장으로 자동 이어집니다.'],note:'공식 조회 화면에 맞춘 전용 수집 기능을 합성 테스트로 검증했습니다. 실제 회원 계정의 로그인부터 저장까지는 아직 통합 검증하지 않았습니다.'},
{id:'kakaot',name:'카카오 T',mode:'앱 거래확인증',color:'#473a15',url:'https://service.kakaomobility.com/cs/faqs/content/?category=16',steps:['카카오 T 앱에서 내 정보 → 이용기록을 여세요.','이용 건의 거래확인증 → 발급하기를 선택하세요.','저장·공유한 이미지나 PDF를 여기로 가져오세요.'],note:'개인 이용내역의 웹 자동연동은 제공하지 않습니다. 기사님께 직접 결제한 내역은 앱에서 발급되지 않을 수 있습니다.'},
{id:'tmoney',name:'고속버스 · KOBUS',mode:'회원 내역 자동 조회',color:'#ba3060',url:'https://www.kobus.co.kr/mbrs/trprinqr/pymPtInqr.do',steps:['출장 날짜를 선택하고 KOBUS에 로그인할 수 있습니다.','로그인 후 조회 가능한 결제내역에서 실제 이용일에 맞는 건을 찾습니다.','이미 발급받은 영수증 이미지나 PDF는 가져올 수 있습니다.'],note:'홈서버에 회원 조회 어댑터를 구현했습니다. 실제 회원 화면 대조는 아직 필요하며, 왕복 금액처럼 날짜별 배분이 불명확한 건은 완료로 처리하지 않습니다.'},
{id:'airline',name:'항공',mode:'발급 파일 가져오기',color:'#387767',url:'https://www.koreanair.com/',steps:['구매한 항공사 또는 여행사의 예약 상세를 여세요.','e-티켓·결제 영수증을 PDF로 저장하세요.','PDF를 가져오면 날짜와 금액을 인식합니다.'],note:'항공사 회원 계정의 자동 수집은 아직 검증하지 않았습니다. 발급받은 파일을 가져올 수 있으며 외화 내역은 별도 확인이 필요합니다.'},
{id:'socar',name:'쏘카',mode:'앱 · 기업 웹',color:'#007fc7',url:'https://enterprise.socar.kr/bizweb_guide/',steps:['쏘카 앱 이용내역 → 결제내역 → 영수증 보기를 여세요.','매출전표를 이메일로 받거나 이용내역을 저장하세요.','쏘카 기업 웹의 이용내역서 PDF도 가져올 수 있어요.'],note:'개인 영수증은 앱에서 발급합니다. 기업 웹은 별도 프로필과 본인 인증이 필요합니다.'},
];

